### ISSUE TITLE
torch.load(pruned_model)

### ISSUE THREAD

**Issue by wuzhiyang2016** [jacobgil/pytorch-pruning#26]
when i use torch.load() to load pruned model , error happen:    AttributeError: 'module' object has no attribute 'ModifiedVGG16Model',  anyone meet this problem?

**Comment by bidakos** [comment]
@wuzhiyang2016 I've got the same problem. I added the ModifiedVGG16Model class in my test script, with no success. Do you still have the same issue?

**Comment by bidakos** [comment]
@jacobgil Any idea?

**Comment by jacobgil** [comment]
The code in the repo saves the entire model, which is actually a bad practice.
A better way would be to save only the state_dict, and then load it.
Going to change it now to 
```python
state_dict = model.state_dict()'
save(state_dict, 'model.chkpt')
```

Then you can load the model like this:
```python
model = ModifiedVGG16Model()
checkpoint = torch.load(checkpoint_path, \
        map_location=lambda storage, loc: storage)
model.load_state_dict(checkpoint)
model.eval()
```

**Comment by wuzhiyang2016** [comment]
> @wuzhiyang2016 I've got the same problem. I added the ModifiedVGG16Model class in my test script, with no success. Do you still have the same issue?

like the author, when we load the saved model , ModifiedVGG16Model() should be defined

**Comment by mlcoop** [comment]
@jacobgil Hey! There is a problem with size mismatch.  For example: `RuntimeError: Error(s) in loading state_dict for ModifiedVGG16Model:
	size mismatch for features.0.weight: copying a param with shape torch.Size([50, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).
	size mismatch for features.0.bias: copying a param with shape torch.Size([50]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for features.2.weight: copying a param with shape torch.Size([44, 50, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).`

Is there way to solve it ?

**Comment by ms-krajesh** [comment]
> @jacobgil Hey! There is a problem with size mismatch. For example: `RuntimeError: Error(s) in loading state_dict for ModifiedVGG16Model: size mismatch for features.0.weight: copying a param with shape torch.Size([50, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]). size mismatch for features.0.bias: copying a param with shape torch.Size([50]) from checkpoint, the shape in current model is torch.Size([64]). size mismatch for features.2.weight: copying a param with shape torch.Size([44, 50, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).`
> 
> Is there way to solve it ?

@jacobgil : Since the pruned model will be having different in and out filters in each layer. Is there any way to load the pruned model state dictionary with original model class?

**Comment by mlcoop** [comment]
@ms-krajesh Probably not a solution but I just rewrote model architecture with altered layer numbers.

**Comment by Saharkakavand** [comment]
> @ms-krajesh Probably not a solution but I just rewrote model architecture with altered layer numbers.

I trained the vgg and saved the model as pth file. then I load it for pruning some filters of it.
the last conv after pruning is not 512 anymore, some filters are gone.
how Pruning the last conv layer affects the first linear layer of the classifier which is (512 7 7, 4096).
how can I prune the input weights of classifier according to the last conv layer.
